export const ERROR_CODES = {
  // Auth
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",

  // Categories
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  // Transactions
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",

  // Saving Goals
  SAVING_GOAL_NOT_FOUND: "SAVING_GOAL_NOT_FOUND",
  AMOUNT_EXCEEDS_TARGET: "AMOUNT_EXCEEDS_TARGET",

  // General
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const